### ISSUE TITLE
retrieve graph for single sentence input

### ISSUE THREAD

**Issue by knwoo** [snap-stanford/GreaseLM#9]
Hi, thank you for introducing such an intriguing work.

your proposed sub graph retrieval process is customized to Q-A pair input.

What kinds of code snippets should I modify to retrieve a graph for just a single sentence input? 

The reason why I ask is that I'd like to make a custom pipeline that samples ConceptNet's subgraph for given custom string input.

**Comment by XikunZhang** [comment]
In the `preprocess.py` script, I define a conversion function for each dataset to convert the original dataset format into an entailment format (essentially a Q-A pair -> a single declarative sentence). See [here](https://github.com/snap-stanford/GreaseLM/blob/e15b2a492d61a5a6cad84f41ba15991bac74a6f8/preprocess.py#L93) and [here](https://github.com/snap-stanford/GreaseLM/blob/e15b2a492d61a5a6cad84f41ba15991bac74a6f8/preprocess.py#L108).

You want to write a customized conversion function for your dataset. You can refer to the conversion functions of [csqa](https://github.com/snap-stanford/GreaseLM/blob/e15b2a492d61a5a6cad84f41ba15991bac74a6f8/preprocess_utils/convert_csqa.py#L45) and [obqa](https://github.com/snap-stanford/GreaseLM/blob/e15b2a492d61a5a6cad84f41ba15991bac74a6f8/preprocess_utils/convert_obqa.py#L12).
